### ISSUE TITLE
[v2.0.0] Switch to in-house MDS parser

### ISSUE THREAD

**Issue by lmichaelis** [lmichaelis/phoenix#14]
_phoenix_ currently uses [lexy](https://github.com/foonathan/lexy) for parsing model script files. This is only a temporary solution and should be replaced by a self-built parser which can properly take into account the broken scripts originally written by the team at PiranhaBytes (missing parentheses and such; see [b317ad](https://github.com/lmichaelis/phoenix/commit/b317adf5f39710c786f049212c7d72e8aaed288f)).

**Comment by lmichaelis** [comment]
Hey @thokkat and @Try, could you double check this new MDS parser on your end? Since you opened #50/#51, you might have some additional insight into this that I don't have. It would be greatly appreciated :>

You can find the new implementation in [feature/mds-parser](https://github.com/lmichaelis/phoenix/tree/feature/mds-parser).

**Comment by Try** [comment]
Source code look good to me - will do more formal testing new week

**Comment by Try** [comment]
Tested today on G1, G2 - no issues spotted

**Comment by lmichaelis** [comment]
Thanks for the help, @Try :) I'll clean up the code and soon we'll be lexy-free :)
