### ISSUE TITLE
Parsing zCCSCamera keyframes

### ISSUE THREAD

**Issue by Try** [lmichaelis/phoenix#27]
There are multiple warnings in command line:
```
[phoenix] vob_tree: encountered unknown VOb [% § 0 25125]
[phoenix] vob_tree: encountered unknown VOb [% § 0 25126]
[phoenix] vob_tree: encountered unknown VOb [% § 0 25127]
[phoenix] vob_tree: encountered unknown VOb [% § 0 25128]
[phoenix] vob_tree: encountered unknown VOb [% § 0 25129]
[phoenix] vob_tree: encountered unknown VOb [% § 0 25130]
```
AFAIR `§` is a special way to refer keyframe in cameras

**Comment by lmichaelis** [comment]
All I know is that they are empty objects and they are [not parsed by ZenLib either](https://github.com/Try/ZenLib/blob/master/zenload/zCVob.cpp#L568-L578). Since we know about them though, `phoenix` now no longer outputs this warning message (see 193a7dc0355d5c8e36973f88f87823b2ea555a73).
