### ISSUE TITLE
Build order polution with libsquish

### ISSUE THREAD

**Issue by Try** [lmichaelis/phoenix#41]
After building OpenGothic, sub-module `OpenGothic\lib\phoenix\vendor\libsquish` becomes modifyed: 
```
HEAD detached at b28220d
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   vendor/libsquish (modified content)
...
HEAD detached at ae7054a
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   squish_export.h
```

I'm not sure, if this header usefull at all. Also part of that: libsquish is only to implement `texture::as_rgba8`, right? Can it be removed eventually?

**Comment by lmichaelis** [comment]
I've noticed this as well. I'll see if there is a way to disable generation of that header or move it into CMake's build directory. That would probably the best solution since I do want to keep `as_rgba8` around since it makes working with textures a lot easier.

It could be moved into `ext` at some point though which might be a good compromise if I then allow disabling it. That would require you to provide an implementation of the DXT formats though.

**Comment by Try** [comment]
> That would require you to provide an implementation of the DXT formats though.

Right now, in `Resources::implLoadTexture` DXT1,2,3,4,5 are handled by Tempest::Pixmap explicitly, and rest uses `as_rgba8`.
(nitpick: actually not supported DXT2/4, but no one uses then anyway)

Rest formats:
* tex_B8G8R8A8
* tex_R8G8B8A8 // supported!
* tex_A8B8G8R8
* tex_A8R8G8B8
* tex_B8G8R8
* tex_R8G8B8 // no hardware support, emulated in Tempest as RGBX
* tex_A4R4G4B4
* tex_A1R5G5B5 // maybe `VK_FORMAT_R5G5B5A1_UNORM_PACK16` (81% support), but still require conversion
* tex_R5G6B5  // Useful!. TODO for Tempest
* tex_p8 

Probably need to clarify here. In engine there is only one component order R-G-B-A for data-storage. This is strategic kind of choose, to avoid potential problems with compute-shaders and blitting. For sampler-capable images, there is a dx12-style component mappings in sampler, what is not very helpful here. 

Current idea is to move conversion workload to OpenGothic `resources.cpp`, since those formats are quite a legacy.
Another thing that I'm worry a little after looking at the code is redundant data copies. `[input] buffer` -> `texture` -> `texture_to_dds/as_rgba8` -> `Tempest::Pixmap` -> host-visible -> gpu.
Probably need to do a profiler run and check it out eventually.

**Comment by lmichaelis** [comment]
I'll think about it. libsquish is a bit heavy and I'd like to drop dependencies anyways (I am currently working on removing lexy which is used for MDS parsing).

But I am at least able to fix the issue. It's kinda hacky but my pipelines work so it seems fine. I applied some changes to lmichaelis/phoenix-libsquish which is used as the source: [15d3f56](https://github.com/lmichaelis/phoenix-libsquish/commit/15d3f56131ed2d76705ed96fa54dc3ed7a058306) and [c8e060c](https://github.com/lmichaelis/phoenix-libsquish/commit/c8e060c6f5dc919b813b5cc04389ce3f5d007b31).

[trial/squish-update](https://github.com/lmichaelis/phoenix/tree/trial/squish-update) has the changes. Will do some extra checks before merging but so far it seems fine.

**Comment by lmichaelis** [comment]
Merged.

**Comment by Try** [comment]
Fixed, thanks!
