### ISSUE TITLE
MDS file parsing stops early

### ISSUE THREAD

**Issue by thokkat** [lmichaelis/phoenix#50]
In OpenGothic the size of `p.animations` is smaller for some mds files than if using a pre-phoenix build. E.g. for `HumanS.mds` only the first 279 of 864 entries are loaded resulting in stuck npc behavior. 

This is only a issue for G1, in G2 there's no difference. 

```c++
Animation::Animation(phoenix::model_script &p, std::string_view name, const bool ignoreErrChunks) {
  ref = std::move(p.aliases);

  for(auto& ani : p.animations) {
```
https://github.com/Try/OpenGothic/blob/fc1c1343028fb92dbb7b5c1f7ed67b4294b800b3/game/graphics/mesh/animation.cpp#L33

**Comment by lmichaelis** [comment]
Hey @thokkat, thanks for the report! I did find something while pre-merge testing that is probably this exact issue though I wasn't able to find the cause. I'll look into it :)

**Comment by lmichaelis** [comment]
Preliminary fix is now available. Changes made are detailed in the commit message :)

**Comment by thokkat** [comment]
Got this error message while parsing `Lurker.mds`
```gdb
error: while parsing mds::dsl_integer
     │
 336 │ ⇨⇨⇨⇨*eventTag⇨("DEF_HIT_LIMB"⇨⇨"BIP01 L PONYTAIL1")
     │                ^ peek failure
error: while parsing mds::dsl_integer
     │
 336 │ ⇨⇨⇨⇨*eventTag⇨("DEF_HIT_LIMB"⇨⇨"BIP01 L PONYTAIL1")
     │                ^ expected digit.decimal

loading error: failed parsing resource of type syntax error
```

**Comment by lmichaelis** [comment]
I've checked all vanilla MDS files manually to make sure they are fully parsed. Trough that I've found two more quirks which are now fixed. This is just a temporary solution while I'm implementing a parser that does not use lexy.

There are just too many quirks and programming errors in the source files to keep the current parser around for long. It's already horrible to work with.

**Comment by thokkat** [comment]
Works, thanks for the quick fix.
