### ISSUE TITLE
Gothic1: T_DIALOGGESTURE_** are not loaded

### ISSUE THREAD

**Issue by Try** [lmichaelis/phoenix#51]
Noticed at top level testing in OpenGothic, presumable those were not loaded due to potential error in model-script parsing. 
Do not have much more info at this point, can do extra testing, if needed.

Version: Steam
Parser: text based (lexy)

**Comment by lmichaelis** [comment]
Hi @Try,
I fixed some MDS problems in #50. Does this problem occur with the latest commit on `main`?

**Comment by Try** [comment]
Yep, fixed. Thanks!
