### ISSUE TITLE
Potential typo in soft-skin mesh

### ISSUE THREAD

**Issue by Try** [lmichaelis/phoenix#53]
https://github.com/lmichaelis/phoenix/blob/2f6748717e3f88c6c02836e81ac3c7aa6640ae7d/source/softskin_mesh.cc#L52-L58

The code around suggest `resize` instead of `reserve`.

**Comment by lmichaelis** [comment]
Hi @Try, sorry for the delay. It's not a typo but still something worth changing. Thanks for reporting :) It's changed in 55325da9.
